// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Đồ_án_Cuối_kỳ_Desktop.Data;

#nullable disable

namespace Đồ_án_Cuối_kỳ_Desktop.Migrations
{
    [DbContext(typeof(QuanLySanCauLongContext))]
    [Migration("20260514075547_CreateNhanVienTableFinal")]
    partial class CreateNhanVienTableFinal
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Đồ_án_Cuối_kỳ_Desktop.Models.BangGia", b =>
                {
                    b.Property<int>("MaGia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MaGia"));

                    b.Property<TimeSpan>("DenGio")
                        .HasColumnType("time(6)");

                    b.Property<decimal>("GiaTheoGio")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("LoaiNgay")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("MaLoai")
                        .HasColumnType("int");

                    b.Property<string>("TenKhungGio")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<TimeSpan>("TuGio")
                        .HasColumnType("time(6)");

                    b.HasKey("MaGia");

                    b.HasIndex("MaLoai");

                    b.ToTable("BangGias");
                });

            modelBuilder.Entity("Đồ_án_Cuối_kỳ_Desktop.Models.ChiTietHoaDon", b =>
                {
                    b.Property<int>("MaHD")
                        .HasColumnType("int");

                    b.Property<int>("MaDV")
                        .HasColumnType("int");

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("MaHD", "MaDV");

                    b.HasIndex("MaDV");

                    b.ToTable("ChiTietHoaDons");
                });

            modelBuilder.Entity("Đồ_án_Cuối_kỳ_Desktop.Models.DichVu", b =>
                {
                    b.Property<int>("MaDV")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MaDV"));

                    b.Property<string>("DonViTinh")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<decimal>("GiaBan")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("HinhAnh")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("SoLuongTon")
                        .HasColumnType("int");

                    b.Property<string>("TenDV")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("MaDV");

                    b.ToTable("DichVus");
                });

            modelBuilder.Entity("Đồ_án_Cuối_kỳ_Desktop.Models.HoaDon", b =>
                {
                    b.Property<int>("MaHD")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MaHD"));

                    b.Property<decimal>("GiamGiaHoiVien")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime?>("GioRa")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("GioVao")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("MaKH")
                        .HasColumnType("int");

                    b.Property<int>("MaSan")
                        .HasColumnType("int");

                    b.Property<decimal>("PhuThu")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("TienDichVu")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("TienSan")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("TongTien")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("TrangThaiThanhToan")
                        .HasColumnType("int");

                    b.HasKey("MaHD");

                    b.HasIndex("MaKH");

                    b.HasIndex("MaSan");

                    b.ToTable("HoaDons");
                });

            modelBuilder.Entity("Đồ_án_Cuối_kỳ_Desktop.Models.KhachHang", b =>
                {
                    b.Property<int>("MaKH")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MaKH"));

                    b.Property<int>("DiemTichLuy")
                        .HasColumnType("int");

                    b.Property<string>("Hang")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("SDT")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.Property<string>("Sdt")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TenKH")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("MaKH");

                    b.ToTable("KhachHangs");
                });

            modelBuilder.Entity("Đồ_án_Cuối_kỳ_Desktop.Models.LoaiSan", b =>
                {
                    b.Property<int>("MaLoai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MaLoai"));

                    b.Property<string>("TenLoai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("MaLoai");

                    b.ToTable("LoaiSans");
                });

            modelBuilder.Entity("Đồ_án_Cuối_kỳ_Desktop.Models.NgayLe", b =>
                {
                    b.Property<DateTime>("Ngay")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("TenLe")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Ngay");

                    b.ToTable("NgayLes");
                });

            modelBuilder.Entity("Đồ_án_Cuối_kỳ_Desktop.Models.NhanVien", b =>
                {
                    b.Property<int>("MaNV")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MaNV"));

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("MaNV");

                    b.ToTable("NhanViens");
                });

            modelBuilder.Entity("Đồ_án_Cuối_kỳ_Desktop.Models.San", b =>
                {
                    b.Property<int>("MaSan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MaSan"));

                    b.Property<string>("HinhAnh")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("MaLoai")
                        .HasColumnType("int");

                    b.Property<string>("TenSan")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("MaSan");

                    b.HasIndex("MaLoai");

                    b.ToTable("Sans");
                });

            modelBuilder.Entity("Đồ_án_Cuối_kỳ_Desktop.Models.BangGia", b =>
                {
                    b.HasOne("Đồ_án_Cuối_kỳ_Desktop.Models.LoaiSan", "LoaiSan")
                        .WithMany("BangGias")
                        .HasForeignKey("MaLoai")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoaiSan");
                });

            modelBuilder.Entity("Đồ_án_Cuối_kỳ_Desktop.Models.ChiTietHoaDon", b =>
                {
                    b.HasOne("Đồ_án_Cuối_kỳ_Desktop.Models.DichVu", "DichVu")
                        .WithMany("ChiTietHoaDons")
                        .HasForeignKey("MaDV")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Đồ_án_Cuối_kỳ_Desktop.Models.HoaDon", "HoaDon")
                        .WithMany("ChiTietHoaDons")
                        .HasForeignKey("MaHD")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DichVu");

                    b.Navigation("HoaDon");
                });

            modelBuilder.Entity("Đồ_án_Cuối_kỳ_Desktop.Models.HoaDon", b =>
                {
                    b.HasOne("Đồ_án_Cuối_kỳ_Desktop.Models.KhachHang", "KhachHang")
                        .WithMany("HoaDons")
                        .HasForeignKey("MaKH");

                    b.HasOne("Đồ_án_Cuối_kỳ_Desktop.Models.San", "San")
                        .WithMany("HoaDons")
                        .HasForeignKey("MaSan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhachHang");

                    b.Navigation("San");
                });

            modelBuilder.Entity("Đồ_án_Cuối_kỳ_Desktop.Models.San", b =>
                {
                    b.HasOne("Đồ_án_Cuối_kỳ_Desktop.Models.LoaiSan", "LoaiSan")
                        .WithMany("Sans")
                        .HasForeignKey("MaLoai")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoaiSan");
                });

            modelBuilder.Entity("Đồ_án_Cuối_kỳ_Desktop.Models.DichVu", b =>
                {
                    b.Navigation("ChiTietHoaDons");
                });

            modelBuilder.Entity("Đồ_án_Cuối_kỳ_Desktop.Models.HoaDon", b =>
                {
                    b.Navigation("ChiTietHoaDons");
                });

            modelBuilder.Entity("Đồ_án_Cuối_kỳ_Desktop.Models.KhachHang", b =>
                {
                    b.Navigation("HoaDons");
                });

            modelBuilder.Entity("Đồ_án_Cuối_kỳ_Desktop.Models.LoaiSan", b =>
                {
                    b.Navigation("BangGias");

                    b.Navigation("Sans");
                });

            modelBuilder.Entity("Đồ_án_Cuối_kỳ_Desktop.Models.San", b =>
                {
                    b.Navigation("HoaDons");
                });
#pragma warning restore 612, 618
        }
    }
}
